#!/usr/bin/with-contenv bash

echo ":: Checking flexget";

if flexget -V | grep 'Latest'; then
    echo ":: update is available, updating"
    pip install --upgrade flexget
else
    echo ":: flexget is up to date"
fi
